# Generated by Django 3.0.2 on 2020-03-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demenagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date du déménagement')),
                ('volume', models.IntegerField()),
                ('formule', models.CharField(choices=[('F1', '1 Camion + 2 déménageurs'), ('F2', '1 Camion + 3 déménageurs'), ('F3', 'Formule Standard'), ('F4', 'Formule Confort'), ('F5', 'Formule Prestige')], default='F3', max_length=2, verbose_name='Formule choisie')),
                ('commentaire', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Déménagement',
                'verbose_name_plural': 'Déménagements',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
            },
        ),
        migrations.CreateModel(
            name='TypeAdresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(choices=[('DEPART', 'Adresse de départ'), ('ARRIVEE', "Adresse d'arrivée")], default='DEPART', max_length=10)),
            ],
            options={
                'verbose_name': 'Départ/Arrivée',
            },
        ),
        migrations.CreateModel(
            name='OptionSupplementaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('OPT1', "parck d'emballage"), ('OPT2', 'Emballage/Déballage de fragiles'), ('OPT3', 'Emballage/Déballage de non-fragiles'), ('OPT4', 'Montage/Démontage'), ('OPT5', 'Assurance'), ('OPT6', 'Lourds'), ('OPT2', 'Emballage/Déballage de fragiles')], default='OPT3', max_length=4, verbose_name='options supplémentaires')),
                ('demenagements', models.ManyToManyField(blank=True, related_name='option', to='relocation.Demenagement')),
            ],
            options={
                'verbose_name': 'option supplémentaire',
                'verbose_name_plural': 'options supplémentaires',
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de demande du devis')),
                ('reference', models.IntegerField(default='Ref N°: 00-DEV-16022020')),
                ('contactee', models.BooleanField(default=False)),
                ('traitee', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.Prospect')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=100, verbose_name='Rue')),
                ('code_postale', models.CharField(max_length=10, verbose_name='Code postale')),
                ('ville', models.CharField(max_length=20, verbose_name='Ville')),
                ('pays', models.CharField(max_length=20, verbose_name='pays')),
                ('etage', models.IntegerField(verbose_name="Numéro d'étage")),
                ('ascenceur', models.BooleanField(default=True, verbose_name='Ascenceur')),
                ('demenagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.Demenagement')),
                ('type_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.TypeAdresse')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
    ]
