# Generated by Django 3.0.2 on 2020-02-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.IntegerField()),
                ('formula', models.CharField(choices=[('F1', '1 Camion + 2 déménageurs'), ('F2', '1 Camion + 3 déménageurs'), ('F3', 'Formule Standard'), ('F4', 'Formule Confort'), ('F5', 'Formule Prestige')], default='F3', max_length=2)),
                ('comments', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_supplies', models.BooleanField(blank=True, default=False, verbose_name="Fournitures d'emballage")),
                ('packing_unpacking_fragiles', models.BooleanField(blank=True, default=False, verbose_name="Emballage/Déballage d'objets fragiles")),
                ('packing_unpacking_non_fragiles', models.BooleanField(blank=True, default=False, verbose_name="Emballage/Déballage d'objets non fragiles")),
                ('disassembly_assembly', models.BooleanField(blank=True, default=False, verbose_name='Démontage/remontage')),
                ('moving_insurance', models.BooleanField(blank=True, default=False, verbose_name='Assurance déménagement')),
                ('heavy_items', models.BooleanField(blank=True, default=False, verbose_name='Objets lourds')),
                ('relocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.Relocation')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_line', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('elevator', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.LocationCategory')),
                ('relocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.Relocation')),
            ],
        ),
    ]
