# Generated by Django 3.0.3 on 2020-02-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocation',
            name='volume',
            field=models.FloatField(default=0.0, verbose_name='volume'),
            preserve_default=False,
        ),
    ]
