# Generated by Django 3.0.2 on 2020-03-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='demenagement',
            field=models.ForeignKey(db_column='demenagement_id', on_delete=django.db.models.deletion.CASCADE, to='relocation.Demenagement'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type_adresse',
            field=models.ForeignKey(db_column='type_adresse_id', on_delete=django.db.models.deletion.CASCADE, to='relocation.TypeAdresse'),
        ),
        migrations.AlterField(
            model_name='optionsupplementaire',
            name='demenagements',
            field=models.ManyToManyField(blank=True, db_column='demenagement_id', related_name='option', to='relocation.Demenagement'),
        ),
    ]
