# Generated by Django 3.0.3 on 2020-02-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0002_relocation_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demenagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relocation_date', models.DateTimeField(verbose_name='date')),
                ('comment', models.CharField(max_length=200, verbose_name='commentaire')),
                ('volume', models.FloatField(verbose_name='volume')),
            ],
        ),
        migrations.DeleteModel(
            name='Relocation',
        ),
    ]
