# Generated by Django 3.0.2 on 2020-02-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0002_auto_20200216_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_line', models.CharField(max_length=100, verbose_name='Rue')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postale')),
                ('city', models.CharField(max_length=20, verbose_name='Ville')),
                ('floor', models.IntegerField(verbose_name="Numéro d'étage")),
                ('elevator', models.BooleanField(default=True, verbose_name='Ascenceur')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='AddressCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_arrival', models.CharField(choices=[('DEPARTURE', 'Adresse de départ'), ('ARRIVAL', "Adresse d'arrivée")], default='DEPARTURE', max_length=10)),
            ],
            options={
                'verbose_name': 'Départ/Arrivée',
            },
        ),
        migrations.CreateModel(
            name='EstimateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de demande du devis')),
                ('reference', models.IntegerField(default='Ref N°: 00-DEV-16022020')),
                ('contacted', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='PackageOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_supplies', models.BooleanField(blank=True, default=False, verbose_name="Fournitures d'emballage")),
                ('packing_unpacking_fragiles', models.BooleanField(blank=True, default=False, verbose_name="Emballage/Déballage d'objets fragiles")),
                ('packing_unpacking_non_fragiles', models.BooleanField(blank=True, default=False, verbose_name="Emballage/Déballage d'objets non fragiles")),
                ('disassembly_assembly', models.BooleanField(blank=True, default=False, verbose_name='Démontage/remontage')),
                ('moving_insurance', models.BooleanField(blank=True, default=False, verbose_name='Assurance déménagement')),
                ('heavy_items', models.BooleanField(blank=True, default=False, verbose_name='Objets lourds')),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name': 'option supplémentaire',
                'verbose_name_plural': 'options supplémentaires',
            },
        ),
        migrations.RemoveField(
            model_name='options',
            name='relocation',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Prospect', 'verbose_name_plural': 'Prospects'},
        ),
        migrations.AlterModelOptions(
            name='relocation',
            options={'ordering': ['date'], 'verbose_name': 'Déménagement', 'verbose_name_plural': 'Déménagements'},
        ),
        migrations.RemoveField(
            model_name='relocation',
            name='available',
        ),
        migrations.RemoveField(
            model_name='relocation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='relocation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='relocation',
            name='processed',
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='relocation',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date du déménagement'),
        ),
        migrations.AlterField(
            model_name='relocation',
            name='formula',
            field=models.CharField(choices=[('F1', '1 Camion + 2 déménageurs'), ('F2', '1 Camion + 3 déménageurs'), ('F3', 'Formule Standard'), ('F4', 'Formule Confort'), ('F5', 'Formule Prestige')], default='F3', max_length=2, verbose_name='Formule choisie'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationCategory',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.AddField(
            model_name='packageoptions',
            name='relocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relocation.Relocation'),
        ),
        migrations.AddField(
            model_name='estimaterequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.Customer'),
        ),
        migrations.AddField(
            model_name='estimaterequest',
            name='relocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relocation.Relocation'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.AddressCategory'),
        ),
        migrations.AddField(
            model_name='address',
            name='relocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation.Relocation'),
        ),
    ]
