# Generated by Django 3.0.3 on 2020-02-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0003_auto_20200226_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsSupplementaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_column='libelle', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='demenagement',
            name='comment',
        ),
        migrations.AddField(
            model_name='demenagement',
            name='commentaire',
            field=models.CharField(db_column='commentaire', default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demenagement',
            name='volume',
            field=models.FloatField(db_column='volume'),
        ),
        migrations.CreateModel(
            name='DemenagementOptionsSupplementaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demenagement', models.ForeignKey(db_column='demenagement_id', on_delete=django.db.models.deletion.CASCADE, to='relocation.Demenagement')),
            ],
        ),
    ]
