# Generated by Django 3.0.3 on 2020-02-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0004_auto_20200226_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionsSupplementaire',
            new_name='OptionSupplementaire',
        ),
        migrations.AddField(
            model_name='demenagementoptionssupplementaire',
            name='option_supplementaire',
            field=models.ForeignKey(db_column='option_supplementaire_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='relocation.OptionSupplementaire'),
            preserve_default=False,
        ),
    ]
