# Generated by Django 3.0.3 on 2020-02-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0005_auto_20200226_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAdresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_column='libelle', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(db_column='rue', max_length=200)),
                ('cp', models.CharField(db_column='cp', max_length=10)),
                ('ville', models.CharField(db_column='ville', max_length=100)),
                ('pays', models.CharField(db_column='pays', max_length=100)),
                ('demenagement', models.ForeignKey(db_column='demenagement_id', on_delete=django.db.models.deletion.CASCADE, to='relocation.Demenagement')),
                ('type_adresse', models.ForeignKey(db_column='type_adresse_id', on_delete=django.db.models.deletion.PROTECT, to='relocation.TypeAdresse')),
            ],
        ),
    ]
