# Generated by Django 3.0.3 on 2020-03-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0006_adresse_typeadresse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='demenagement',
            options={'verbose_name': 'Déménagement', 'verbose_name_plural': 'Déménagements'},
        ),
        migrations.AlterModelOptions(
            name='typeadresse',
            options={'verbose_name': 'Départ/Arrivée'},
        ),
        migrations.RenameField(
            model_name='demenagement',
            old_name='relocation_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='adresse',
            name='ascenceur',
            field=models.BooleanField(db_column='ascenceur', default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adresse',
            name='etage',
            field=models.IntegerField(db_column='etage', default=0),
        ),
        migrations.AddField(
            model_name='demenagement',
            name='option_supplementaires',
            field=models.ManyToManyField(to='relocation.OptionSupplementaire'),
        ),
        migrations.AlterField(
            model_name='typeadresse',
            name='libelle',
            field=models.CharField(choices=[('DEPART', 'Adresse de départ'), ('ARRIVEE', "Adresse d'arrivée")], db_column='libelle', max_length=60),
        ),
        migrations.DeleteModel(
            name='DemenagementOptionsSupplementaire',
        ),
    ]
